Repository equinor/resdata, pull requests merged in 2023-01, with the labels that each got.

#893 Remove py27 relics, black everything
  .github/workflows/style.yml
  cmake/create_cmakelists.py
  install/install.py
  python/docs/examples/avg_pressure.py
  python/docs/examples/cmp_nnc.py
  python/docs/examples/grid_info.py
  python/ecl/ecl_type.py
  python/ecl/eclfile/ecl_3dkw.py
  python/ecl/eclfile/ecl_kw.py
  python/ecl/grid/faults/fault_line.py
  python/ecl/rft/ecl_rft.py
  python/ecl/util/geometry/geometry_tools.py
  python/ecl/util/util/stringlist.py
  python/tests/ecl_tests/test_fault_blocks.py
  python/tests/util_tests/test_string_list.py
  requirements.txt
  setup.cfg
  setup.py
Labels: maintenance

#891 clang-format: Remove version check
  .github/workflows/style.yml
  CMakeLists.txt
  script/clang-format
Labels: maintenance

#881 Improve deprecation warning for EclGrid.createRectangular
  python/ecl/grid/ecl_grid.py
Labels: blocked

#897 Circumvent Pandas bugs for years > 2262
  python/ecl/summary/ecl_sum.py
  python/tests/ecl_tests/test_ecl_sum.py
Labels: bug
